pipeline {
    agent { node { label 'AGENT-1' } }

    stages {
        stage('Init') {
            steps {
                sh '''
                 cd 01-vpc
                 ls -ltr
                 pwd
                 terraform init
                '''           
            }
        }
        stage('Plan') {
            steps {
                 sh '''
                    cd 01-vpc
                    ls -ltr
                    pwd
                    terraform plan
                '''       
            }
        }       
    }
      post { 
        always { 
            echo 'I will always run whether job is success or not'
        }
        success{
            echo 'I will run only when job is success'
        }
        failure{
            echo 'I will run when failure'
        }
    }
}

